// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBwGR_dHiPg5GYV3lZ1rNLSLui2O7La2Y',
    appId: '1:269069396327:android:09f1164a9430699e60e7c2',
    messagingSenderId: '269069396327',
    projectId: 'metw-d3270',
    databaseURL: 'https://metw-d3270-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'metw-d3270.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHsH23ergqgYtWB1pdjz3zzoZ_hHPQy0Y',
    appId: '1:269069396327:ios:3df2f5bcfda263d760e7c2',
    messagingSenderId: '269069396327',
    projectId: 'metw-d3270',
    databaseURL: 'https://metw-d3270-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'metw-d3270.firebasestorage.app',
    iosBundleId: 'com.evyx.metwGo',
  );

}